### ISSUE TITLE
Request: Add License file to the repo

### ISSUE THREAD

**Issue by HeadClot** [asantoni/survivalism#8]
Would it be possible to add a license file to this repo? 

I am asking because I am looking at using some of your code for a learning project. Namely the multi-server travel / Sharding code.

**Comment by asantoni** [comment]
Done: MIT license. 
https://github.com/asantoni/survivalism/blob/master/LICENSE

Please keep in mind there are third party resources in this repository and you should check the license of those before reusing any assets: https://github.com/asantoni/survivalism/blob/master/src/CREDITS

Most of the code is mine and MIT licensed, but there are some other bits under "Other ACS Code" in the `CREDITS` file. All the multi-server travel and sharding code is mine and you're encouraged to reuse it and make something cool out of it. :)

**Comment by HeadClot** [comment]
Thank you so much :)
